"""Golden regression guard for the Stage R-23 F.1 confirmatory smoke.

The test reads the local `data/analytics/silver` and `data/analytics/gold`
outputs generated by the R-23 smoke. It is skipped when those local smoke
outputs were wiped, matching the archive sentinel pattern used for R-22.
"""
from __future__ import annotations

import json
import math

from pathlib import Path
from typing import Any

import pandas as pd
import pytest

_ROOT = Path(__file__).resolve().parents[2]
_SILVER_DIR = _ROOT / "data" / "analytics" / "silver"
_GOLD_DIR = _ROOT / "data" / "analytics" / "gold"
_EXPECTED_PATH = (
    Path(__file__).parent / "fixtures" / "f1_golden" / "expected.json"
)


def _smoke_output_available() -> bool:
    required_gold = [
        _GOLD_DIR / "gold_quality_statistics_report.parquet",
        _GOLD_DIR / "gold_oos_quality_report.parquet",
        _GOLD_DIR / "gold_prediction_metrics_by_run_split_horizon.parquet",
        _GOLD_DIR / "gold_quantile_degeneracy_report.parquet",
    ]
    required_silver_roots = [
        _SILVER_DIR / "dim_run",
        _SILVER_DIR / "fact_oos_predictions",
    ]
    return all(path.exists() for path in required_gold) and all(
        root.exists() and any(root.rglob("*.parquet"))
        for root in required_silver_roots
    )


def _expected() -> dict[str, Any]:
    return json.loads(_EXPECTED_PATH.read_text(encoding="utf-8"))


def _read_gold(table: str) -> pd.DataFrame:
    return pd.read_parquet(_GOLD_DIR / f"{table}.parquet")


def _read_silver(table: str) -> pd.DataFrame:
    paths = sorted((_SILVER_DIR / table).rglob("*.parquet"))
    if not paths:
        return pd.DataFrame()
    return pd.concat((pd.read_parquet(path) for path in paths), ignore_index=True)


def _assert_close(actual: float, expected: float, *, rtol: float) -> None:
    assert math.isclose(actual, expected, rel_tol=rtol, abs_tol=rtol), (
        f"expected {expected}, got {actual}"
    )


@pytest.mark.skipif(
    not _smoke_output_available(),
    reason="R-23 smoke silver/gold outputs are not present on this checkout",
)
def test_f1_golden_smoke_statistics_ready_for_test_horizons() -> None:
    expected = _expected()
    sweep_id = expected["sweep_id"]
    rtol = float(expected["rtol"])

    stats = _read_gold("gold_quality_statistics_report")
    actual = stats[
        stats["parent_sweep_id"].eq(sweep_id)
        & stats["split"].eq("test")
        & stats["horizon"].isin([1, 7])
    ].copy()

    assert set(actual["horizon"]) == {1, 7}
    assert actual["statistics_ready"].eq(True).all()

    for horizon, expected_row in expected["quality_statistics_test"].items():
        row = actual.loc[actual["horizon"].eq(int(horizon))].iloc[0]
        for column, expected_value in expected_row.items():
            actual_value = row[column]
            if isinstance(expected_value, float):
                _assert_close(float(actual_value), expected_value, rtol=rtol)
            else:
                assert actual_value == expected_value, (
                    f"horizon={horizon} column={column}: "
                    f"expected {expected_value}, got {actual_value}"
                )


@pytest.mark.skipif(
    not _smoke_output_available(),
    reason="R-23 smoke silver/gold outputs are not present on this checkout",
)
def test_f1_golden_smoke_oos_quality_has_zero_failed_rows() -> None:
    expected = _expected()
    sweep_id = expected["sweep_id"]
    expected_quality = expected["gold_oos_quality_report"]

    quality = _read_gold("gold_oos_quality_report")
    failed_rows = int(quality["passed"].ne(True).sum())
    sweep_failed_rows = int(
        quality.loc[quality["parent_sweep_id"].eq(sweep_id), "passed"].ne(True).sum()
    )

    assert len(quality) == expected_quality["n_rows"]
    assert failed_rows == expected_quality["failed_rows"] == 0
    assert sweep_failed_rows == expected_quality["sweep_failed_rows"] == 0


@pytest.mark.skipif(
    not _smoke_output_available(),
    reason="R-23 smoke silver/gold outputs are not present on this checkout",
)
def test_f1_golden_smoke_parent_sweep_id_coverage_across_gold_tables() -> None:
    expected = _expected()
    sweep_id = expected["sweep_id"]
    expected_coverage = expected["gold_parent_sweep_id_coverage"]

    gold_files = {path.stem: path for path in sorted(_GOLD_DIR.glob("gold_*.parquet"))}
    assert len(gold_files) == expected["gold_table_count"] == 25
    assert set(gold_files) == set(expected_coverage)

    for table, table_expected in expected_coverage.items():
        df = pd.read_parquet(gold_files[table])
        assert len(df) == table_expected["n_rows"], table
        assert df.shape[1] == table_expected["n_cols"], table

        if table_expected["n_rows"] == 0:
            # Optional explainability tables are 0x0 in this smoke; there are
            # no rows on which a parent_sweep_id value could be asserted.
            assert df.empty, table
            continue

        assert "parent_sweep_id" in df.columns, table
        assert df["parent_sweep_id"].eq(sweep_id).any(), table
        assert int(df["parent_sweep_id"].isna().sum()) == table_expected[
            "null_parent_sweep_id_rows"
        ], table


@pytest.mark.skipif(
    not _smoke_output_available(),
    reason="R-23 smoke silver/gold outputs are not present on this checkout",
)
def test_f1_golden_smoke_probabilistic_metrics_match_fixture() -> None:
    expected = _expected()
    sweep_id = expected["sweep_id"]
    rtol = float(expected["rtol"])
    expected_metrics = expected["probabilistic_metrics"]

    qdeg = _read_gold("gold_quantile_degeneracy_report")
    qdeg_quantile = qdeg[
        qdeg["parent_sweep_id"].eq(sweep_id)
        & qdeg["prediction_mode"].eq("quantile")
    ]
    assert len(qdeg_quantile) == expected_metrics["quantile_degeneracy_rows"]
    _assert_close(
        float(qdeg_quantile["p10_eq_p90_rate"].max()),
        expected_metrics["max_p10_eq_p90_rate"],
        rtol=rtol,
    )
    assert bool(qdeg_quantile["gate_passed"].all()) is expected_metrics[
        "all_degeneracy_gates_passed"
    ]

    metrics = _read_gold("gold_prediction_metrics_by_run_split_horizon")
    probabilistic = metrics[
        metrics["parent_sweep_id"].eq(sweep_id)
        & metrics["n_probabilistic_samples"].gt(0)
    ]
    assert len(probabilistic) == expected_metrics["probabilistic_metric_rows"]
    _assert_close(
        float(probabilistic["mpiw_post_guardrail"].min()),
        expected_metrics["min_mpiw_post_guardrail"],
        rtol=rtol,
    )
    _assert_close(
        float(probabilistic["pred_interval_width_post_guardrail"].min()),
        expected_metrics["min_pred_interval_width_post_guardrail"],
        rtol=rtol,
    )

    dim_run = _read_silver("dim_run")
    sweep_run_ids = set(
        dim_run.loc[dim_run["parent_sweep_id"].eq(sweep_id), "run_id"]
    )
    predictions = _read_silver("fact_oos_predictions")
    predictions = predictions[predictions["run_id"].isin(sweep_run_ids)]
    raw_quantile = predictions[
        ["quantile_p10", "quantile_p50", "quantile_p90"]
    ].notna().all(axis=1)
    raw_crossing = raw_quantile & (
        predictions["quantile_p10"].gt(predictions["quantile_p50"])
        | predictions["quantile_p50"].gt(predictions["quantile_p90"])
    )
    post_guardrail_quantile = predictions[
        [
            "quantile_p10_post_guardrail",
            "quantile_p50_post_guardrail",
            "quantile_p90_post_guardrail",
        ]
    ].notna().all(axis=1)
    post_guardrail_crossing = post_guardrail_quantile & (
        predictions["quantile_p10_post_guardrail"].gt(
            predictions["quantile_p50_post_guardrail"]
        )
        | predictions["quantile_p50_post_guardrail"].gt(
            predictions["quantile_p90_post_guardrail"]
        )
    )

    assert int(raw_quantile.sum()) == expected_metrics["raw_quantile_rows"]
    assert int(raw_crossing.sum()) == expected_metrics["raw_crossing_rows"] == 0
    _assert_close(
        float(raw_crossing.sum() / raw_quantile.sum()),
        expected_metrics["raw_crossing_rate"],
        rtol=rtol,
    )
    assert int(post_guardrail_crossing.sum()) == expected_metrics[
        "post_guardrail_crossing_rows"
    ] == 0
